ALTER TABLE loans
  ADD COLUMN IF NOT EXISTS payment_status ENUM('UPCOMING', 'UNPAID', 'PARTIAL', 'PAID') NOT NULL DEFAULT 'UPCOMING' AFTER balance;

UPDATE loans
SET payment_status = CASE
  WHEN balance <= 0 THEN 'PAID'
  WHEN paid > 0 THEN 'PARTIAL'
  ELSE 'UPCOMING'
END;
